### ISSUE TITLE
TypeError: only length-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by Algabri** [mbeyeler/opencv-python-blueprints#24]
when I run the code chapter6.py

I got this error.
```
/usr/bin/python2.7 /home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/chapter6.py
feature None
 - strategy one-vs-one
    - train
Traceback (most recent call last):
  File "/home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/chapter6.py", line 77, in <module>
    main()
  File "/home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/chapter6.py", line 44, in main
    MCS.fit(X_train, y_train)
  File "/home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/classifiers.py", line 258, in fit
    params=self.params)
TypeError: only length-1 arrays can be converted to Python scalars

Process finished with exit code 1
```

as you see, python 2.7
opencv 3.3
please help me to fix this error.
Thank you in advance

**Comment by mbeyeler** [comment]
Thanks for posting. It is not immediately clear to me what is causing this error. It seems to be caused by the `train` function of the OpenCV classifier.

I suspect either `X_train` or `y_train_bin` on [L256](https://github.com/mbeyeler/opencv-python-blueprints/blob/master/chapter6/classifiers.py#L256) has length 1, and that is causing some issues with the classifier's `train` function. Can you add a print statement right before that to see what `X_train[data_id, :]`, `y_train_bin`, and `self.params` look like?

**Comment by Algabri** [comment]
Thanks, @mbeyeler 
The outputs are:

```
X_train [[  85.   96.  127. ...,  100.  104.  113.]
 [  19.   18.   17. ...,   71.  103.  132.]
 [  93.   92.  186. ...,   11.    8.    9.]
 ..., 
 [  22.   20.   21. ...,   76.   62.   44.]
 [  30.   29.   30. ...,   28.   28.   29.]
 [  75.   89.   90. ...,  241.  225.  233.]]
 - strategy one-vs-one
    - train
y_train_bin [0 1 0 ..., 1 1 0]
```

**Comment by mbeyeler** [comment]
Looks all good. I think the problem is that they changed the OpenCV API to `train(samples, layout, responses)`, similar to what is explained [here](https://github.com/rcrespocano/opencv-python/issues/4).

Try adding a `layout` parameter to [L256](https://github.com/mbeyeler/opencv-python-blueprints/blob/master/chapter6/classifiers.py#L256):

```
self.classifiers[svm_id].train(X_train[data_id, :], cv2.ml.ROW_SAMPLE, y_train_bin)
```

**Comment by Algabri** [comment]
Thanks, yes.
It is fine now.
Sorry, @mbeyeler. I wrote this answer before appearing this error.
I already change it to `self.classifiers.append(cv2.ml.SVM_create())` but it is still giving error.
Another error:

```
Traceback (most recent call last):
  File "/home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/chapter6.py", line 78, in <module>
    main()
  File "/home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/chapter6.py", line 49, in main
    acc, prec, rec = MCS.evaluate(X_test, y_test)
  File "/home/redhwan/Downloads/opencv-python-blueprints-master/chapter6/classifiers.py", line 298, in evaluate
    y_hat = self.classifiers[svm_id].predict_all(X_test_id)
AttributeError: 'cv2.ml_SVM' object has no attribute 'predict_all'
```
